[package]
name = "wati2wat"
version = "0.1.0"
authors = ["UltimateProGrammer <63370104+UltimatePro-Grammer@users.noreply.github.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = "~2.33"
regex = "1"
colored = "2"